spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/StartUp
    username: postgres
    password: 123
    driver-class-name: org.postgresql.Driver


  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    show-sql: true